name: CI Pipeline

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      NEXT_PUBLIC_API_BASE_URL: http://localhost:4000/api
      JWT_SECRET: test_jwt_secret
      YYC3_YY_DB_HOST: localhost
      YYC3_YY_DB_USER: test_user
      YYC3_YY_DB_PASSWORD: test_pass
      YYC3_YY_DB_NAME: yyc3_yy_test
      REDIS_URL: redis://localhost:6380/0
      EMAIL_HOST: smtp.test.com
      EMAIL_PORT: 1025
      EMAIL_USER: test@ktv.local
      EMAIL_PASSWORD: test_email_pass
      EMAIL_FROM: test@ktv.local

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit Tests (Jest)
        run: npm run test

      - name: Build
        run: npm run build

      - name: Start server
        run: npm run start &
        env:
          PORT: 4000

      - name: Wait for server
        run: npx wait-on http://localhost:4000

      - name: E2E Tests (Playwright)
        run: npx playwright test
